import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useCart} from '../hooks/use-cart'
import Link from 'next/link'

import products from "../products.json"



export default function Home() {
  const {addToCart} = useCart();

  return (
    <div className={styles.container}>
      <Head>
        <title>Style yourself!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/'>
          <a>
            <h1 className={styles.title}>
              Style yourself!
            </h1>
          </a>
        </Link>

        <p className={styles.description}>
          The best swag store on the web!
        </p>

        
        <ul className={styles.grid}>
          {products.map(product => {
            const {id, title, price, description, image} = product;
            return(
              <li key={id} className={styles.card}>
                <Link href={`/products/${id}`}>
                  <a>
                    <img src={image} alt={title} />
                    <h3>{title}</h3>
                    <p>₹{price}</p>
                    <p>{description}</p>
                  </a>
                </Link>
                <p>
                  <button className={styles.button} onClick={() =>
                    addToCart({
                      id
                    })
                  }>Add to Cart</button>
                </p>
              </li>
            )
          })}
        </ul>
      </main>

      
    </div>
  )
}
